# AWS Certified Professional Compose File
version: '3'

services:
  nextjs:
    image:  acp-ui:latest
    tty: true
    stdin_open: true
    volumes:
      - ./acp-ui:/app
    ports:
      - 3000:3000
  db:
    image:  mariadb:10.10.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sqlpass
      - MYSQL_DATABASE=nflqna
      - MYSQL_USER=nflqna
      - MYSQL_PASSWORD=sqlpass
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306